build_from:
  aarch64: "alpine:3.20"
  amd64: "alpine:3.20"
  armhf: "alpine:3.20"
  armv7: "alpine:3.20"
  i386: "alpine:3.20"
labels:
  org.opencontainers.image.title: "Home Assistant Add-on: ddclient"
  org.opencontainers.image.description: "ddclient add-on"
  org.opencontainers.image.source: "https://github.com/jameskorzekwa/ha-ddclient"
  org.opencontainers.image.licenses: "Apache License 2.0"
