name: "ddclient"
description: "ddclient"
version: "0.0.1"
slug: "ddclient"
url: "https://github.com/jameskorzekwa/ha-ddclient/tree/main/ha-ddclient/"
init: false
arch:
  - aarch64
  - amd64
  - armhf
  - armv7
  - i386
map:
  - share
image: "ghcr.io/jameskorzekwa/{arch}-ha-ddclient"
